{{ range .Values.oAuthProxyServices }}
---
{{- $service := . -}}
{{- if .ingress.enabled -}}
{{- if and .ingress.className (not (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .ingress.annotations "kubernetes.io/ingress.class" .ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ default (printf "oauth2-proxy-%s" .name) .ingress.overwriteName }}
  namespace: {{ default "monitoring" .namespace }}
  labels:
    {{- include "she-sso.labels" $ | nindent 4 }}
  {{- with .ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .ingress.className (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .ingress.className }}
  {{- end }}
  {{- if .ingress.tls }}
  tls:
    {{- range .ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      {{- if .secretName}}
      secretName: {{ .secretName }}
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $host := .ingress.hosts }}
    - host: {{ $host.host | quote }}
      http:
        paths:
          - path: {{ default "/oauth2" $host.path }}
            {{- if and $host.pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ $host.pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ default (printf "oauth2-proxy-%s" $service.name) $service.service.overwriteName }}
                port:
                  {{- if (regexMatch "[0-9]+$" ($service.service.port | toString)) }}
                  number: {{ $service.service.port }}
                  {{- else }}
                  name: {{ default "http" $service.service.port }}
                  {{- end }}
              {{- else }}
              serviceName: {{ default (printf "oauth2-proxy-%s" $service.name) $service.service.overwriteName }}
              servicePort: {{ default "http" $service.service.port }}
              {{- end }}
    {{- end }}
{{- end }}
{{- end }}
