{{- if .Values.s3monitoringEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: deployment
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "common.labels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: pod
        {{- include "common.labels" . | nindent 8 }}
    spec:
      containers:
      - name: nginx
        image: nginx
        resources: {}
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: metrics-volume
      - name: cron
        image: sheitag/s3df
        resources: {}
        volumeMounts:
        - mountPath: /app/s3df.conf
          name: config-file
          readOnly: true
        - mountPath: /app/html
          name: metrics-volume
      imagePullSecrets:
      - name: docker-regcred
      volumes:
      - name: config-file
        secret:
          secretName: {{ .Release.Name }}-secret
      - name: metrics-volume
        emptyDir:
          sizeLimit: 10Mi
{{- end }}
