{{- if .Values.prometheusEnabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-prometheus-rules
  namespace: {{ default .Release.Namespace .Values.prometheusNamespace }}
  labels:
    app.kubernetes.io/component: prometheus-rule
    {{- include "common.labels" . | nindent 4 }}
    {{- if .Values.prometheusLabels }}
      {{- toYaml .Values.prometheusLabels | nindent 4 }}
    {{- end }}
spec:
  groups:
  - name: {{ .Release.Name }}.rules
    {{- with .Values }}
    rules:

    - alert: S3_QuotaLimitBytesWarning
      labels:
        context: s3
        severity: warning
      annotations:
        summary: "S3 storage space warning"
        description: "S3 storage space utilization of AccessKeyID {{`{{`}} $labels.access_key_id {{`}}`}} reached {{`{{`}} $value | printf \"%.1f\" {{`}}`}}%."
      expr: |-
        s3_percentage_used_total >= 100 - s3_percentage_free_total_warn
      for: 1h
    - alert: S3_QuotaLimitBytesCritical
      labels:
        context: s3
        severity: critical
      annotations:
        summary: "S3 storage space critical"
        description: "S3 storage space utilization of AccessKeyID {{`{{`}} $labels.access_key_id {{`}}`}} reached {{`{{`}} $value | printf \"%.1f\" {{`}}`}}%."
      expr: |-
        s3_percentage_used_total >= 100 - s3_percentage_free_total_crit
      for: 1h

    - alert: S3_QuotaLimitPercentageWarning
      labels:
        context: s3
        severity: warning
      annotations:
        summary: "S3 storage space warning"
        description: "S3 storage space of AccessKeyID {{`{{`}} $labels.access_key_id {{`}}`}} at {{`{{`}} $value | humanize1024 {{`}}`}}B."
      expr: |-
        s3_bytes_used_total >= s3_bytes_quota_limit - s3_bytes_free_total_warn
      for: 1h
    - alert: S3_QuotaLimitPercentageCritical
      labels:
        context: s3
        severity: critical
      annotations:
        summary: "S3 storage space critical"
        description: "S3 storage space of AccessKeyID {{`{{`}} $labels.access_key_id {{`}}`}} at {{`{{`}} $value | humanize1024 {{`}}`}}B."
      expr: |-
        s3_bytes_used_total >= s3_bytes_quota_limit - s3_bytes_free_total_crit
      for: 1h

    {{- end}}
{{- end }}
