{{- if .Values.prometheusEnabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-prometheus-rules
  namespace: {{ .Values.prometheusNamespace }}
  labels:
    {{- .Values.prometheusLabels | toYaml | nindent 4 }}
spec:
  groups:
  - name: {{ .Release.Name }}.rules
    {{- with .Values }}
    rules:
    - alert: S3_ApproachingQuotaLimit
      labels:
        context: s3
        severity: warning
      annotations:
        summary: "Approaching S3 quota limit"
        description: "More than {{ .warningPercentageUsed }}% used or less than {{ .warningBytesLeft }} bytes left"
      expr: |-
        (s3_percentage_used_total{access_key_id={{ $.Values.accessKeyID }}} >= {{ default 80 .warningPercentageUsed }})
        or
        ({{ default 0 .warningBytesLeft }} > 1 and {{ $.Values.quotaLimit }} - s3_bytes_used_total{access_key_id={{ $.Values.accessKeyID }}} <= {{ .warningBytesLeft }})
      for: {{ default "3h" .warningDuration }}
    - alert: S3_HittingQuotaLimit
      labels:
        context: s3
        severity: critical
      annotations:
        summary: "Hitting S3 quota limit"
        description: "More than {{ .criticalPercentageUsed }}% used or less than {{ .criticalBytesLeft }} bytes left"
      expr: |-
        s3_percentage_used_total{access_key_id={{ $.Values.accessKeyID }}} >= {{ default 95 .criticalPercentageUsed }}
        or
        ({{ default 0 .criticalBytesLeft }} > 1 and {{ $.Values.quotaLimit }} - s3_bytes_used_total{access_key_id={{ $.Values.accessKeyID }}} <= {{ .criticalBytesLeft }})
      for: {{ default "1h" .criticalDuration }}
    {{- end}}
{{- end }}
