{{- if .Values.prometheusEnabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-prometheus-rules
  namespace: {{ default .Release.Namespace .Values.prometheusNamespace }}
  labels:
    app.kubernetes.io/component: prometheus-rule
    {{- include "common.labels" . | nindent 4 }}
    {{- if .Values.prometheusLabels }}
      {{- toYaml .Values.prometheusLabels | nindent 4 }}
    {{- end }}
spec:
  groups:
  - name: {{ .Release.Name }}.rules
    {{- with .Values }}
    rules:

    - alert: S3_ApproachingQuotaLimitPercentage
      labels:
        context: s3
        severity: warning
      annotations:
        summary: "Approaching S3 quota limit"
        description: "Reached or exceeded {{ .warningPercentageUsed }}% of the quota limit"
      expr: |-
        s3_percentage_used_total{access_key_id="{{ .accessKeyID | default "none" }}"} >= {{ .warningPercentageUsed }}
      for: {{ .warningDuration }}

    - alert: S3_ApproachingQuotaLimitAbsolute
      labels:
        context: s3
        severity: warning
      annotations:
        summary: "Approaching S3 quota limit"
        description: "Less than {{ .warningBytesFree }} bytes left"
      expr: |-
        {{ .quotaLimit }} - s3_bytes_used_total{access_key_id="{{ .accessKeyID | default "none" }}"} <= {{ .warningBytesFree }}
      for: {{ .warningDuration }}

    - alert: S3_CriticalQuotaLimitPercentage
      labels:
        context: s3
        severity: critical
      annotations:
        summary: "Hitting S3 quota limit"
        description: "Reached or exceeded {{ .criticalPercentageUsed }}% of the quota limit"
      expr: |-
        s3_percentage_used_total{access_key_id="{{ .accessKeyID | default "none" }}"} >= {{ .criticalPercentageUsed }}
      for: {{ .criticalDuration }}

    - alert: S3_CriticalQuotaLimitAbsolute
      labels:
        context: s3
        severity: critical
      annotations:
        summary: "Hitting S3 quota limit"
        description: "Less than {{ .criticalBytesFree }} bytes left"
      expr: |-
        {{ .quotaLimit }} - s3_bytes_used_total{access_key_id="{{ .accessKeyID | default "none" }}"} <= {{ .criticalBytesFree }}
      for: {{ .criticalDuration }}

    {{- end}}
{{- end }}
