---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "logging.fullname" . }}-filebeat
  labels:
    {{- include "logging.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - nodes
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - "apps"
  resources:
  - replicasets
  - replicasets/scale
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "jobs"
  resources:
  - batch
  verbs:
  - get
  - list
  - watch
