---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ include "logging.fullname" . }}
  labels:
    {{- include "logging.labels" . | nindent 4 }}
spec:
  {{- include "kibana.spec" . | nindent 2 }}
