---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-yaml
      exclude: ^charts/.*/templates/.*\.yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: mixed-line-ending
  - repo: https://github.com/norwoodj/helm-docs
    rev:  v1.12.0
    hooks:
      - id: helm-docs
        args:
          - --chart-search-root=charts
          - --template-files=./README.md.gotmpl
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
      - id: helmlint
