{{- if .Values.indexTemplates.defaultTemplates.access }}
apiVersion: opensearch.opster.io/v1
kind: OpensearchIndexTemplate
metadata:
  name: {{ include "logging-opensearch.fullname" . }}-access
  labels:
    {{- include "logging-opensearch.labels" . | nindent 4 }}
spec:
  name: access
  {{- with .Values.global.opensearchCluster }}
  opensearchCluster:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  indexPatterns:
    - "access-*"
  dataStream:
    timestamp_field:
      name: "@timestamp"
  priority: 1
  template:
    {
      "mappings": {
        "dynamic": "false",
        "properties": {
          "remote_addr": {
            "type": "keyword",
            "ignore_above": 256
          },
          "user_identity": {
            "type": "keyword",
            "ignore_above": 256
          },
          "method": {
            "type": "keyword",
            "ignore_above": 256
          },
          "request_uri": {
            "type": "text"
          },
          "protocol": {
            "type": "keyword",
            "ignore_above": 256
          },
          "status": {
            "type": "integer"
          },
          "bytes_sent": {
            "type": "integer"
          },
          "referrer": {
            "type": "text"
          },
          "user_agent": {
            "type": "text"
          },
          "request_length": {
            "type": "integer"
          },
          "request_time": {
            "type": "float"
          },
          "proxy_upstream_name": {
            "type": "keyword",
            "ignore_above": 256
          },
          "upstream_addr": {
            "type": "keyword",
            "ignore_above": 256
          },
          "upstream_response_length": {
            "type": "integer"
          },
          "upstream_response_time": {
            "type": "float"
          },
          "upstream_status": {
            "type": "integer"
          },
          "req_id": {
            "type": "keyword",
            "ignore_above": 256
          },
          "kubernetes": {
            "type": "object",
            "properties": {
              "namespace_name": {
                "type": "keyword",
                "ignore_above": 256
              },
              "pod_id": {
                "type": "keyword",
                "ignore_above": 256
              },
              "pod_name": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "log": {
            "type": "text"
          },
          "stream": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      }
    }
  version: 1
{{- end }}
