{{- if .Values.opensearch.indexTemplates.defaultTemplates.container }}
apiVersion: opensearch.opster.io/v1
kind: OpensearchIndexTemplate
metadata:
  name: {{ include "logging-opensearch.name" . }}-container
  namespace: {{ .Release.Namespace | default "logging" }}
  labels:
    {{- include "logging-opensearch.labels" . | nindent 4 }}
spec:
  name: container
  opensearchCluster:
    name: {{ include "logging-opensearch.opensearchName" . }}
  indexPatterns:
    - "container-*"
  dataStream:
    timestamp_field:
      name: "@timestamp"
  dataStream: {}
  priority: 1
  template:
    {
      "mappings": {
        "dynamic": "false",
        "properties": {
          "kubernetes": {
            "type": "object",
            "properties": {
              "annotations": {
                "dynamic": "true",
                "type": "object"
              },
              "container_image": {
                "type": "keyword",
                "ignore_above": 256
              },
              "container_name": {
                "type": "keyword",
                "ignore_above": 256
              },
              "docker_id": {
                "type": "keyword",
                "ignore_above": 256
              },
              "host": {
                "type": "keyword",
                "ignore_above": 256
              },
              "labels": {
                "dynamic": "false",
                "type": "object"
              },
              "namespace_name": {
                "type": "keyword",
                "ignore_above": 256
              },
              "pod_id": {
                "type": "keyword",
                "ignore_above": 256
              },
              "pod_name": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "log": {
            "type": "text"
          },
          "stream": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      }
    }
  version: 1
{{- end }}
