{{- if .Values.opensearch.enabled }}
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: {{ include "logging-opensearch.opensearchName" . }}
  namespace: {{ .Release.Namespace | default "logging" }}
  labels:
    {{- include "logging-opensearch.labels" . | nindent 4 }}
spec:
  {{- with .Values.opensearch.settings }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
