{{- range $role := .Values.opensearch.roles }}
{{- $role_users := list }}
{{- range $user := $.Values.opensearch.users }}
{{- if ( has $role.name $user.roles ) }}
{{- $role_users = append $role_users $user.name }}
{{- end }}
{{- end }}
{{- if gt ( len $role_users ) 0 }}
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchUserRoleBinding
metadata:
  name: {{ include "logging-opensearch.name" $ }}-{{ $role.name }}
  labels:
    {{- include "logging-opensearch.labels" $ | nindent 4 }}
spec:
  {{- range $key := ( list "opensearchCluster" ) }}
  {{- toYaml ( default ( pick $.Values.global $key ) ( pick $role $key ) ) | nindent 2 }}
  {{- end }}
  {{- with $role.name }}
  roles:
    - {{ . }}
  {{- end }}
  {{- with $role_users }}
  users:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
