apiVersion: v2
type: application
name: logging-opensearch
description: A Helm chart which deploys a Opensearch cluster manifests, its configuation and fluent bit
dependencies:
  - name: fluent-bit
    alias: fluentbit
    repository: https://fluent.github.io/helm-charts
    version: 0.46.7
appVersion: "1.2.3"
version: 1.2.3
