{{ if and .Values.logging.enabled .Values.logging.podMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "monitoring-rules.fullname" . }}-logging-filebeat
  labels:
    {{- include "monitoring-rules.labels" . | nindent 4 }}
    {{ toYaml .Values.prometheusLabels | nindent 4 }}
spec:
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
  selector:
    matchLabels:
      todo: TODO
{{ end }}
