{{ if .Values.kubernetes.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "monitoring-rules.fullname" . }}-kubernetes
  labels:
    {{- include "monitoring-rules.labels" . | nindent 4 }}
    {{ toYaml .Values.prometheusLabels }}
spec:
  groups:
  - name: node-rules
    rules:
    {{- if not ( default false .Values.kubernetes.disabledRules.masterIsMissing ) }}
    - alert: MasterIsMissing
      expr: count(kube_node_role{role="{{ required "Must define role of master node!" .Values.kubernetes.masterIsMissing.role }}"} offset 1h) by (node) unless count(kube_node_role{role="{{ required "Must define role of master node!" .Values.kubernetes.masterIsMissing.role }}"}) by (node)
      for: 60s
      labels:
        service: kubernetes
        severity: critical
      annotations:
        summary: {{` 'Master node {{ $labels.node }} is missing!' `}}
        description: {{` 'One of the master nodes {{ $labels.node }} which was present one hour ago went missing!' `}}
    {{- end }}
    {{- if not ( default false .Values.kubernetes.disabledRules.wrongAmountOfMasters ) }}
    - alert: WrongAmountOfMaster
      expr: count(kube_node_role{role="{{ required "Must define role of master node!" .Values.kubernetes.masterIsMissing.role }}"}) < {{ required "Must define expected amount of master!" .Values.kubernetes.masterIsMissing.amount }} 
      for: 60s
      labels:
        service: kubernetes
        severity: critical
      annotations:
        summary: {{` 'Amount of master node {{ $value }} is mismatching!' `}}
        description: {{`'The actual amount of master nodes {{ $value }} is differs to the expected`}} {{ .Values.kubernetes.masterIsMissing.amount }} {{`nodes!'`}}
    {{- end }}
{{ end }}
