{{- with .Values.prometheusOperator -}}
{{- if .enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: '{{ include "argo.targetCluster.name" $ }}-{{ include "application.name" . }}'
spec:
  project: {{ include "argo.project" $ }}
  source:
    repoURL: {{ .source.repoURL }}
    targetRevision: {{ .source.targetRevision }}
    chart: {{ .source.chart }}
    helm:
      values: |
        {{- if .alertmanager.enabled }}
        alertmanager:
          {{- if .alertmanager.ingress.enabled }}
          ingress:
            ingressClassName: {{ .alertmanager.ingress.className }}
            enabled: true
            hosts:
              - alertmanager.{{ .alertmanager.ingress.baseUrl }}
            tls:
              - hosts:
                 - alertmanager.{{ .alertmanager.ingress.baseUrl }}
            annotations:
              nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
              nginx.ingress.kubernetes.io/backend-protocol: HTTP
          extraArgs:
              - --insecure
          {{- end }}
        {{- end }}
        {{- if .grafana.enabled }}
        grafana:
          {{- if .grafana.ingress.enabled }}
          ingress:
            ingressClassName: {{ .grafana.ingress.className }}
            enabled: true
            hosts:
              - grafana.{{ .grafana.ingress.baseUrl }}
            tls:
              - hosts:
                 - grafana.{{ .grafana.ingress.baseUrl }}
            annotations:
              nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
              nginx.ingress.kubernetes.io/backend-protocol: HTTP
          extraArgs:
              - --insecure
          sidecar:
            dashboard:
              enabled: true
              label: grafana_dashboard
          grafana.ini:
            analytics:
              check_for_updates: true
            log:
              mode: console file
              level: debug
            grafana_net:
              url: https://grafana.net
            server:
              domain: "grafana.{{ .grafana.ingress.baseUrl }}"
              root_url: https://grafana.{{ .grafana.ingress.baseUrl }}
              router_logging: true
              enforce_domain: true
            auth:
              sigv4_verbose_logging: true
          {{- end }}
        {{- end }}
        {{- if .prometheus.enabled }}
        prometheus:
          prometheusSpec:
            additionalScrapeConfigs:
              {{- if .prometheus.crunchyPostgresExporter.enabled }}
              - job_name: 'crunchy-postgres-exporter'
                kubernetes_sd_configs:
                  - role: pod
                relabel_configs:
                  - source_labels: [__meta_kubernetes_pod_label_postgres_operator_crunchydata_com_crunchy_postgres_exporter,__meta_kubernetes_pod_label_crunchy_postgres_exporter]
                    action: keep
                    regex: true
                    separator: ""
                  - source_labels: [__meta_kubernetes_pod_container_port_number]
                    action: drop
                    regex: 5432
                  - source_labels: [__meta_kubernetes_pod_container_port_number]
                    action: drop
                    regex: 10000
                  - source_labels: [__meta_kubernetes_pod_container_port_number]
                    action: drop
                    regex: 8009
                  - source_labels: [__meta_kubernetes_pod_container_port_number]
                    action: drop
                    regex: 2022
                  - source_labels: [__meta_kubernetes_pod_container_port_number]
                    action: drop
                    regex: ^$
                  - source_labels: [__meta_kubernetes_namespace]
                    action: replace
                    target_label: kubernetes_namespace
                  - source_labels: [__meta_kubernetes_pod_name]
                    target_label: pod
                  - source_labels: [__meta_kubernetes_pod_label_postgres_operator_crunchydata_com_cluster,__meta_kubernetes_pod_label_pg_cluster]
                    target_label: cluster
                    separator: ""
                    replacement: '$1'
                  - source_labels: [__meta_kubernetes_namespace,cluster]
                    target_label: pg_cluster
                    separator: ":"
                    replacement: '$1$2'
                  - source_labels: [__meta_kubernetes_pod_ip]
                    target_label: ip
                    replacement: '$1'
                  - source_labels: [__meta_kubernetes_pod_label_postgres_operator_crunchydata_com_instance,__meta_kubernetes_pod_label_deployment_name]
                    target_label: deployment
                    replacement: '$1'
                    separator: ""
                  - source_labels: [__meta_kubernetes_pod_label_postgres_operator_crunchydata_com_role,__meta_kubernetes_pod_label_role]
                    target_label: role
                    replacement: '$1'
                    separator: ""
                  - source_labels: [dbname]
                    target_label: dbname
                    replacement: '$1'
                  - source_labels: [relname]
                    target_label: relname
                    replacement: '$1'
                  - source_labels: [schemaname]
                    target_label: schemaname
                    replacement: '$1'
              {{- end }}
            serviceMonitorSelector:
              matchExpressions:
                - {key: release, operator: In, values: [{{.prometheus.serviceMonitorSelectors}}]}
          {{- if .prometheus.ingress.enabled }}
          ingress:
            ingressClassName: {{ .prometheus.ingress.className }}
            enabled: true
            hosts:
              - prometheus.{{ .prometheus.ingress.baseUrl }}
            tls:
              - hosts:
                 - prometheus.{{ .prometheus.ingress.baseUrl }}
            annotations:
              nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
              nginx.ingress.kubernetes.io/backend-protocol: HTTP
          extraArgs:
              - --insecure
          {{- end }}
        {{- end }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: '{{ include "argo.targetCluster" $ }}'
    namespace: {{ include "application.namespace" . }}

---
{{- end }}
{{- end }}
