{
 "title": "Database Versions",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "versions",
    "query": {
     "query": "count_values(\"version\", ccp_postgresql_version_current{role=\"master\"})"
    }
   },
   {
    "name": "pgo_version_major",
    "query": {
     "query": "label_values(kube_pod_container_info{image=~\"^.*postgres-operator:.*$\"}, image)"
    }
   },
   {
    "name": "pgo_version_minor",
    "query": {
     "query": "label_values(kube_pod_container_info{image=~\"^.*postgres-operator:.*$\"}, image)"
    }
   },
   {
    "name": "pgo_version_patch",
    "query": {
     "query": "label_values(kube_pod_container_info{image=~\"^.*postgres-operator:.*$\"}, image)"
    }
   },
   {
    "name": "pgo_version_build",
    "query": {
     "query": "label_values(kube_pod_container_info{image=~\"^.*postgres-operator:.*$\"}, image)"
    }
   },
   {
    "name": "pgo_version",
    "query": {
     "query": "label_values(kube_pod_container_info{image=~\"^.*postgres-operator:.*$\"}, image)"
    }
   },
   { "name": "versions2", "query": "140007, 150002" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Versions Share",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"version\", ccp_postgresql_version_current{role=\"master\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operator Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_info{image=~\"^.*postgres-operator:.*$\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database Versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Versions ($versions2)",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 10 },
   "repeat": "versions2",
   "targets": [
    {
     "expr": "((0 * ccp_database_size_bytes{role=\"master\"}) + on (pg_cluster) group_left ccp_postgresql_version_current{role=\"master\"}) == $versions2",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}