name: Check that docs are generated

on: push

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart: [ grafana-dashboards, kyverno-policies, logging, monitoring-rules, s3-monitoring, she-runtime]

    steps:
      - name: Checkout
        uses: 
      - uses: gabe565/setup-helm-docs-action@v1
      - run: helm-docs
        working-directory: './charts/${{ matrix.chart }}'
      - run: |
          find ./charts -type f -name README.md -exec sed -i '$ d' {} \;
          git add -N .
          git diff --quiet || (echo '::error::Please make sure that the README.md is up to date' && exit 1)
